version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: patent_backend
    ports:
      - "3001:3001"
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: patent_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
